// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7NJHlPNuRLFpDHXxcuJsx_DwI9aRN-I',
    appId: '1:916829487557:web:2fb0db3c041a32ccd44bac',
    messagingSenderId: '916829487557',
    projectId: 'brisko-20395',
    authDomain: 'brisko-20395.firebaseapp.com',
    databaseURL: 'https://brisko-20395-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'brisko-20395.firebasestorage.app',
    measurementId: 'G-CK7JYLZMBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkpVrGHAfOmC6jgVO5UVbTwjeIMEE3vYA',
    appId: '1:916829487557:android:04f942abbfbca31ad44bac',
    messagingSenderId: '916829487557',
    projectId: 'brisko-20395',
    databaseURL: 'https://brisko-20395-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'brisko-20395.firebasestorage.app',
  );
}
