// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-0uJU_5ye61yB5hu-uziEsWMKbQyPgs',
    appId: '1:867560517197:web:269128931f75dd7972b604',
    messagingSenderId: '867560517197',
    projectId: 'briskoapp-6ec77',
    authDomain: 'briskoapp-6ec77.firebaseapp.com',
    databaseURL: 'https://briskoapp-6ec77-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'briskoapp-6ec77.firebasestorage.app',
    measurementId: 'G-6N4F1LJRVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZpeE0F7DqmWno91zctJmOFcKrJEe5gM4',
    appId: '1:867560517197:android:8b77bc113e6db7ce72b604',
    messagingSenderId: '867560517197',
    projectId: 'briskoapp-6ec77',
    databaseURL: 'https://briskoapp-6ec77-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'briskoapp-6ec77.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi8CzK3KM_eCzSO1CqeHNqEk0Kg8ZOK44',
    appId: '1:867560517197:ios:5adeca287178f77b72b604',
    messagingSenderId: '867560517197',
    projectId: 'briskoapp-6ec77',
    databaseURL: 'https://briskoapp-6ec77-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'briskoapp-6ec77.firebasestorage.app',
    iosBundleId: 'com.briskopizza.app',
  );
}
